version: '3.7'

services:
  backend:
    build: 
      context: ./memoryproject

    ports:
      - "8000:8000"
    env_file:
      - ./memoryproject/memoryproject/.env
    depends_on:
      - db

  frontend:
    build: ./memoryproject/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./memoryproject/frontend/.env
    depends_on:
      - backend

  db:
    image: "postgres:15"
    env_file:
      - ./memoryproject/memoryproject/.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: